### ISSUE TITLE
Multiple IPFS daemons per Cluster peer

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#483]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement

#### Description

I was thinking one solution to the scalabilty problems that Raft has might be to simply allow plugging in many IPFS daemons to the same IPFS Cluster instance. Thus, having a reduced number of cluster peers (i.e. 10) might support distributing pinsets to 500 ipfs daemons (if we associate 50 daemons to each peer).

That way, we'd keep a high availability cluster with a highly available shared pinset and allow to use it to push contents to hundreds (thousands?) of ipfs Peers without pushing the limits of Raft.

It is also a way to do collaborative clusters in a way in which the user doesn't need to run Cluster at all, it just needs to open the API of their IPFS daemon and be included in one of the trusted-cluster peers.

This would mean some changes to the architecture, but seems doable:

* Supporting multiple IPFSConnectors (one per daemon)
* PinTracker definition of `Remote` would change.
* Reworking the concept of allocations (currently they happen per cluster peer, but they would need to be associated to a peer + daemon)
* Metrics should be not only from cluster peer, but rather each peer would produce metrics for every attached daemon
* Probably a bunch of other considerations I can't even think about right now

**Comment by hsanjuan** [comment]
Basically: Raft won't scale nicely to a thousand peers. Too much chatter. It's not about storing, it's about the limitations of the protocol. But we need to actually test how many peers is ok.

**Comment by lanzafame** [comment]
Raft may not but Serf will, see: https://www.serf.io/docs/internals/simulator.html

**Comment by hsanjuan** [comment]
Serf does not implement consensus. The problem is not a too large peerset, it is providing consensus mechanisms on it.

**Comment by lanzafame** [comment]
Ahh I understand what you are getting at now 👍

**Comment by hsanjuan** [comment]
Closing this, now that we have a way to scale number of peers in the cluster. If running with multiple ipfs daemons, simply run several cluster peers.
