### ISSUE TITLE
Open FIXMEs in sharding

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#496]
As we come closer to merging the sharding branch and officially supporting local adding through IPFS, this issue tracks all of the open issues that are remaining in the sharding code in order to actually support sharding.

* [ ] ipfs-cluster-ctl pin ls and status should probably filter out all shard and cluster dag pins out, using only data-pins and meta-pins. Extra flags should allow displaying the others.
* [ ] when checking the Pin for errors for a ShardType pin, we have no way to know if the MaxDepth should be 1 or 2 (if we added one extra level), or more (if we supported many extra levels). We should decide what we check once we know what MaxDepths are possible.
* [ ] Sharding two files which share significant similarities may result in producing some shards which are the same for both. Unpinning one of them will then unpin the shard that is used by the other. We handled this problem by tracking `Parents` per shard and placing the , but this requires patching the shards when the cluster dag is known, and updating them when a parent is unpinned etc. It is probably easier to make  each shard pin "unique" for a ClusterDAG. But this will result in not being able to re-use an already allocated shard. We might also just load all clusterDAGs when unpinning one of them, and check that each shard is not part of any other clusterDAG. A bit like garbage collection on ipfs.
* [ ] `IPFSPinStatus` type should probably make distinctions for Recursive and Depth Limited pins. This depends on how IPFS presents that.
* [ ] `IPFSPinStatus.IsPinned(depth)` should return true only if the status is pinned to the given depth. Related to above.
* [ ] `ipfs-cluster-ctl` should enable sharding flags for adding when it's supported
* [ ] Is it possible to display total progress while adding? Things don't look pretty on ipfs on this front.
* [ ] We have a 4MB limitation on the size of blocks. We should keep track of how big our shard block is and flush it before it hits the limit. There is some commented code.
* [ ] Related to above: we should use a custom IPLD block format(s) for cluster. This would allow recovering cluster DAGs from IPFS without cluster and gives us further control on how data formats (currently its a cbored-map with ipld-cbor).
* [ ] We could dinamically adjust the shard size to the smallest available space in the allocations. But this would require that we use disk-informer metrics and not something else, and that we drop the whole informer abstraction, or request those metrics on the side. It's also not clear how useful it is, as probably results in really small shards as space runs out and doesn't fix the fact that there is no space.
* [ ] Our sharding dag service carries a `cid.Set` to avoid putting the same block on several shards because the ipfs adder tends to send the same block several times or simply because the chunker (say rabin) outputs the same blocks. This means that we keep all the sharded object CIDs in memory. Maybe there is a better way to determine if we have already processed a Cid (and skip it then), at least with some probability.

All of these show up as FIXMEs and TODOs in the code.

**Comment by hsanjuan** [comment]
* [ ] The operations which involve the pintrackers re-queuing `Pin` objects (Recover at least) must set the right PinOptions on them. Currently they just do `PinCid(cid)`. But recovering should set MaxDepth correctly in the case of non standard pins.

**Comment by hsanjuan** [comment]
* [ ] We have a problem in the sharding DagService because it is automatically wrapped in  a `Batch` DagService by the importers and this results in a) concurrent calls to Add (which causes concurrent map writes) b) broken adder, because we might Finalize shards before the last blocks have been Added() from the importer, because it's adding them asynchronously after closing a batch. I was fixing a) but it's probably worth to take this and fix it in the `importers` project. Started discussion here: https://github.com/ipfs/go-unixfs/issues/27

**Comment by 0zAND1z** [comment]
I am very much interested in the sharding support for ipfs-cluster.

From the [roadmap](https://cluster.ipfs.io/documentation/roadmap/ ), it looks like there is a plan to tackle this in the next 6 months to 8 months.

Are there any active PRs or discourse threads working on this objective? Happy to collaborate.

**Comment by hsanjuan** [comment]
@0zAND1z this is blocked on the fact that ipfs can only pin fully recursively or directly, but not to a certain max-depth as cluster needs. Unfortunately a fix on this is falls on go-ipfs land and not likely to come to come anytime soon.
